### YamlMime:Lifecycle
metadata:
  title: Microsoft Intelligent Application Gateway 2007
  description: Microsoft Intelligent Application Gateway 2007은 고정 수명 주기 정책을 따릅니다.
  ms.date: 07/28/2020
  ms.openlocfilehash: c3c1ca3898de2c0ac61b79395f1c75e4689d91980dbeb4f5641b05160088230d
  ms.sourcegitcommit: 1c28c95e7a2b743cff45216da63f72ffbad026ed
  ms.translationtype: HT
  ms.contentlocale: ko-KR
  ms.lasthandoff: 08/06/2021
  ms.locfileid: "2495152"
name: Microsoft Intelligent Application Gateway 2007
summary: >
  Microsoft Intelligent Application Gateway 2007은 [고정](/lifecycle/policies/fixed) 수명 주기 정책을 따릅니다.



  > [!IMPORTANT]

  > 이 제품에 대한 지원이 종료되었습니다. 아래 마이그레이션 지침을 참조하세요.
products:
- microsoft-servers
policyType: fixed
supportDates:
  start: 06/01/2007
  end: 07/10/2012
  extendedEnd: 07/11/2017
releases:
- version: Service Pack 2
  startDate: 11/27/2008
  endDate: 07/11/2017
- version: Service Pack 1
  startDate: 09/03/2007
  endDate: 01/12/2010
- version: Original Release
  startDate: 06/01/2007
  endDate: 10/14/2008
content: "\n## <a name=\"links\"></a>링크 \n* [Microsoft Intelligent Application Gateway 2007 로드맵](/archive/blogs/testtesttestbug/important-changes-to-the-forefront-product-line)\n* [서비스 팩 정책](/lifecycle/policies/fixed#service-packs)"
