### YamlMime:Lifecycle
metadata:
  title: Microsoft 지능형 응용 프로그램 게이트웨이 2007
  description: Microsoft 지능형 응용 프로그램 게이트웨이 2007 고정 수명 주기 정책을 따릅니다.
  ms.date: 07/28/2020
  ms.openlocfilehash: 6e5cc4784788d27433b7525f6a900cbc1e9f0713
  ms.sourcegitcommit: 9bdc77ca92cba2e3edb432e57b1845247a9ade6e
  ms.translationtype: MT
  ms.contentlocale: ko-KR
  ms.lasthandoff: 07/28/2020
  ms.locfileid: "827315"
name: Microsoft 지능형 응용 프로그램 게이트웨이 2007
summary: >
  Microsoft 지능형 응용 프로그램 게이트웨이 2007 [고정](/lifecycle/policies/fixed) 수명 주기 정책을 따릅니다.



  > [!IMPORTANT]

  > 이 제품에 대 한 지원이 종료 되었습니다. 아래 마이그레이션 지침을 참조 하세요.
products:
- microsoft-servers
policyType: fixed
supportDates:
  start: 06/01/2007
  end: 07/10/2012
  extendedEnd: 07/11/2017
releases:
- version: Service Pack 2
  startDate: 11/27/2008
  endDate: 07/11/2017
- version: Service Pack 1
  startDate: 09/03/2007
  endDate: 01/12/2010
- version: Original Release
  startDate: 06/01/2007
  endDate: 10/14/2008
content: "\n## <a name=\"links\"></a>Links \n* [Microsoft 지능형 응용 프로그램 게이트웨이 2007 로드맵](/archive/blogs/testtesttestbug/important-changes-to-the-forefront-product-line)\n* [서비스 팩 정책](/lifecycle/policies/fixed#service-packs)"
