### YamlMime:Lifecycle
metadata:
  title: Windows Desktops를 위한 Microsoft Application Virtualization Hosting 4.6
  description: Microsoft Application Virtualization Hosting 4.6 for Windows Desktop는 고정 수명 주기 정책을 따릅니다.
  ms.date: 09/01/2020
  keywords: for Windows Desktops
name: Windows Desktops를 위한 Microsoft Application Virtualization Hosting 4.6
summary: |+
  Microsoft Application Virtualization Hosting 4.6 for Windows Desktops는 [고정](/lifecycle/policies/fixed) 수명 주기 정책을 따릅니다.

  Windows Desktops용 버전에 적용됩니다.

products:
  - windows
policyType: fixed
supportDates:
  start: 05/27/2010
  end: 07/14/2015
  extendedEnd: 07/14/2020
releases:
  - version: Service Pack 3
    startDate: 12/02/2013
    endDate: 07/14/2020
  - version: Service Pack 2
    startDate: 10/01/2012
    endDate: 01/13/2015
  - version: Service Pack 1
    startDate: 01/26/2011
    endDate: 10/08/2013
  - version: Original Release
    startDate: 05/27/2010
    endDate: 04/10/2012
content: |

  ## <a name="links"></a>링크 
  * [제품 및 마이그레이션 정보](/microsoft-desktop-optimization-pack/appv-v4/overview-of-application-virtualization)
  * [서비스 팩 정책](/lifecycle/policies/fixed#service-packs)

  > [!NOTE]
  > App-V 4.6 클라이언트가 App-V 4.5 서버를 사용하기 때문에 지원되는 App-V 4.6 클라이언트와 함께 사용할 때 App-V 4.6의 수명 주기 날짜에 따라 App-V 4.5 서버가 계속 지원됩니다.

  ## <a name="editions"></a>버전 
  * Windows Desktops용