### YamlMime:Lifecycle
metadata:
  title: Microsoft Forefront Client Security
  description: Microsoft Forefront Client Security는 고정 수명 주기 정책을 따릅니다.
  ms.date: 08/28/2020
name: Microsoft Forefront Client Security
summary: |+
  Microsoft Forefront Client Security는 [고정](/lifecycle/policies/fixed) 수명 주기 정책을 따릅니다.


products:
  - msc
policyType: fixed
supportDates:
  start: 08/02/2007
  extendedEnd: 07/14/2015
releases:
  - version: Original Release
    startDate: 08/02/2007
    endDate: 07/14/2015
content: |+

  ## <a name="links"></a>링크 
  * [System Center Endpoint Protection](/lifecycle/products/microsoft-system-center-2012-endpoint-protection)

  > [!NOTE]
  > Forefront Client Security는 2015년 7월 14일부터 중단되었습니다. 제품 버전에 대한 지원이 종료되면 맬웨어 방지 및 스파이웨어 방지 정의 업데이트를 더 이상 사용할 수 없습니다. System Center Endpoint Protection을 대안으로 평가하세요.