### YamlMime:Lifecycle
metadata:
  title: Microsoft System Center Configuration Manager 2007
  description: Microsoft System Center Configuration Manager 2007는 고정 수명 주기 정책을 따릅니다.
  ms.date: 07/28/2020
  ms.openlocfilehash: 796670fd93547cc79f69c544085070efb0116650
  ms.sourcegitcommit: 9bdc77ca92cba2e3edb432e57b1845247a9ade6e
  ms.translationtype: MT
  ms.contentlocale: ko-KR
  ms.lasthandoff: 07/28/2020
  ms.locfileid: "827173"
name: Microsoft System Center Configuration Manager 2007
summary: >
  Microsoft System Center Configuration Manager 2007는 [고정](/lifecycle/policies/fixed) 수명 주기 정책을 따릅니다.



  > [!IMPORTANT]

  > 이 제품에 대 한 지원이 종료 되었습니다. 아래 마이그레이션 지침을 참조 하세요.
products:
- msc
policyType: fixed
supportDates:
  start: 11/29/2007
  end: 07/08/2014
  extendedEnd: 07/09/2019
releases:
- version: Service Pack 2
  startDate: 10/22/2009
  endDate: 07/09/2019
- version: Service Pack 1
  startDate: 05/21/2008
  endDate: 01/11/2011
- version: Original Release
  startDate: 11/29/2007
  endDate: 07/14/2009
content: "\n## <a name=\"links\"></a>Links \n* [마이그레이션 지침](/mem/configmgr/core/migration/migrate-data-between-hierarchies)\n* [제품 정보](/mem/configmgr/core/understand/introduction)\n* [서비스 팩 정책](/lifecycle/policies/fixed#service-packs)"
