### YamlMime:Lifecycle
metadata:
  title: Microsoft Application Virtualization 4.6
  description: Microsoft Application Virtualization 4.6은 고정 수명 주기 정책을 따릅니다.
  ms.date: 07/28/2020
  ms.openlocfilehash: 868274b4468e663afe8e1b9f36069490ab4da025
  ms.sourcegitcommit: 9bdc77ca92cba2e3edb432e57b1845247a9ade6e
  ms.translationtype: HT
  ms.contentlocale: ko-KR
  ms.lasthandoff: 07/28/2020
  ms.locfileid: "827298"
name: Microsoft Application Virtualization 4.6
summary: >+
  Microsoft Application Virtualization 4.6은 [고정](/lifecycle/policies/fixed) 수명 주기 정책을 따릅니다.


  Remote Desktop Services, Windows Desktops, Sequencer용 버전에 적용됩니다.

products:
- windows
policyType: fixed
supportDates:
  start: 05/27/2010
  end: 07/14/2015
  extendedEnd: 07/14/2020
releases:
- version: Service Pack 3
  startDate: 12/02/2013
  endDate: 07/14/2020
- version: Service Pack 2
  startDate: 10/01/2012
  endDate: 01/13/2015
- version: Service Pack 1
  startDate: 01/26/2011
  endDate: 10/08/2013
- version: Original Release
  startDate: 05/27/2010
  endDate: 04/10/2012
content: "\n## <a name=\"links\"></a>링크 \n* [제품 및 마이그레이션 정보](/microsoft-desktop-optimization-pack/appv-v4/overview-of-application-virtualization)\n* [마이그레이션 지침](https://techcommunity.microsoft.com/t5/Product-Life-Cycle/FAST-products-approaching-the-end-of-extended-support-in-2018/td-p/101710)\n* [서비스 팩 정책](/lifecycle/policies/fixed#service-packs)\n\n> [!NOTE]\n> App-V 4.6 클라이언트가 App-V 4.5 서버를 사용하기 때문에 지원되는 App-V 4.6 클라이언트와 함께 사용할 때 App-V 4.6의 수명 주기 날짜에 따라 App-V 4.5 서버가 계속 지원됩니다.\n\n## <a name=\"editions\"></a>버전 \n* Remote Desktop Services용\n* Windows Desktops용\n* Sequencer"
