### YamlMime:Lifecycle
metadata:
  title: Windows Desktops를 위한 Microsoft Application Virtualization Hosting 5.0
  description: Microsoft Application Virtualization Hosting 5.0 for Windows Desktops는 고정 수명 주기 정책을 따릅니다.
  ms.date: 09/01/2020
  keywords: for Windows Desktops
name: Windows Desktops를 위한 Microsoft Application Virtualization Hosting 5.0
summary: |+
  Microsoft Application Virtualization Hosting 5.0 for Windows Desktops는 [고정](/lifecycle/policies/fixed) 수명 주기 정책을 따릅니다.

  Windows Desktops용 버전에 적용됩니다.

products:
  - windows
policyType: fixed
supportDates:
  start: 11/01/2012
  end: 01/09/2018
  extendedEnd: 04/14/2026
releases:
  - version: Service Pack 3
    startDate: 12/08/2014
    endDate: 04/14/2026
  - version: Service Pack 2
    startDate: 11/08/2013
    endDate: 01/12/2016
  - version: Service Pack 1
    startDate: 04/10/2013
    endDate: 01/13/2015
  - version: Original Release
    startDate: 11/01/2012
    endDate: 07/08/2014
content: |

  ## <a name="links"></a>링크 
  * [제품 정보](/microsoft-desktop-optimization-pack/appv-v4/overview-of-application-virtualization)
  * [서비스 팩 정책](/lifecycle/policies/fixed#service-packs)


  ## <a name="editions"></a>버전 
  * Windows Desktops용