### YamlMime:Lifecycle
metadata:
  title: Microsoft System Center Configuration Manager 2007 R3
  description: Microsoft System Center Configuration Manager 2007 R3은 고정 수명 주기 정책을 따릅니다.
  ms.date: 07/28/2020
name: Microsoft System Center Configuration Manager 2007 R3
summary: |
  Microsoft System Center Configuration Manager 2007 R3은 [고정](/lifecycle/policies/fixed) 수명 주기 정책을 따릅니다.


  > [!IMPORTANT]
  > 이 제품에 대한 지원이 종료되었습니다. 아래 마이그레이션 지침을 참조하세요.
products:
  - msc
policyType: fixed
supportDates:
  start: 12/19/2010
  end: 07/08/2014
  extendedEnd: 07/09/2019
releases:
  - version: Original Release
    startDate: 12/19/2010
    endDate: 07/09/2019
content: |+

  ## <a name="links"></a>링크 
  * [마이그레이션 지침](/mem/configmgr/core/migration/migrate-data-between-hierarchies)
  * [추가 마이그레이션 지침](/mem/configmgr/core/migration/planning-for-migration)